"""initial tables: admins, bookings, turf_settings

Revision ID: 13a53e9a5687
Revises: 
Create Date: 2026-09-10 17:37:42.644677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a53e9a5687'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('username', name=op.f('uq_admins_username'))
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_code', sa.String(length=12), nullable=False),
    sa.Column('customer_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=14), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('slot_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'BLOCKED')", name=op.f('ck_bookings_booking_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('booking_code', name=op.f('uq_bookings_booking_code'))
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('ix_bookings_status_date', ['status', 'booking_date'], unique=False)
        batch_op.create_index('uq_active_slot', ['booking_date', 'slot_time'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED', 'BLOCKED')"), sqlite_where=sa.text("status IN ('PENDING', 'CONFIRMED', 'BLOCKED')"))

    op.create_table('turf_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turf_name', sa.String(length=80), nullable=False),
    sa.Column('tagline', sa.String(length=160), nullable=True),
    sa.Column('about_text', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('map_embed_url', sa.Text(), nullable=True),
    sa.Column('map_link', sa.Text(), nullable=True),
    sa.Column('facebook_url', sa.Text(), nullable=True),
    sa.Column('opening_hours_text', sa.String(length=160), nullable=True),
    sa.Column('booking_rules_text', sa.Text(), nullable=True),
    sa.Column('confirm_time_text', sa.String(length=160), nullable=True),
    sa.Column('booking_window_days', sa.Integer(), nullable=False),
    sa.Column('max_pending_per_phone', sa.Integer(), nullable=False),
    sa.Column('pricing', sa.JSON(), nullable=False),
    sa.Column('facilities', sa.JSON(), nullable=False),
    sa.Column('reviews', sa.JSON(), nullable=False),
    sa.Column('gallery', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turf_settings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turf_settings')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('uq_active_slot', postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED', 'BLOCKED')"), sqlite_where=sa.text("status IN ('PENDING', 'CONFIRMED', 'BLOCKED')"))
        batch_op.drop_index('ix_bookings_status_date')

    op.drop_table('bookings')
    op.drop_table('admins')
    # ### end Alembic commands ###
